@startuml diagram

title RDRA2.0図
left to right direction

actor 親権者
note "家族の予定を立てたい" as yk1_1
note "家族の予定を知りたい" as yk1_2
note "個人的なタスクを管理したい" as yk1_3
note "タスクによっては予定を紐づけたい" as yk1_4
note "予定に関連して家族と連絡がとりたい" as yk1_5
note "タスクに関連して家族と連絡がとりたい" as yk1_6
note "後から連絡履歴を検索したい" as yk1_7
note "連絡の返事はなるべく早く欲しい" as yk1_8
note "他の家族には予定が埋まっていることだけを伝えたいときもある" as yk1_9
note "被養育者を追加したい" as yk1_10
note "予定とかタスクとか関係なく連絡したい" as yk1_11
note "家族に自分の予定を知らせたい" as yk1_12
note "家族以外には見られたくない" as yk1_13
note "家族の予定はカレンダー上でシンプルに表示して欲しい" as yk1_14
note "家族にタスクをお願いしたい" as yk1_15

actor 被養育者

actor システム管理者
note "色んな家族に利用してもらいたい" as kanri_1
note "障害発生時、ある時点までシステムを戻したい" as kanri_2
note "家族単位でシステムを戻したい" as kanri_3
note "各親権者に最新情報などをお知らせしたい" as kanri_4
note "利用者からの問合せ手段が欲しい" as kanri_5
note "匿名の利用統計情報が欲しい" as kanri_6
note "毎月または毎年の課金の仕組みが欲しい" as kanri_7
note "無料プランもつくりたい" as kanri_8
note "無料プランには広告を表示したい" as kanri_9

親権者 -- yk1_1
親権者 -- yk1_2
親権者 -- yk1_3
親権者 -- yk1_4
親権者 -- yk1_5
親権者 -- yk1_6
親権者 -- yk1_7
親権者 -- yk1_8
親権者 -- yk1_9
親権者 -- yk1_10
親権者 -- yk1_11
親権者 -- yk1_12
親権者 -- yk1_13
親権者 -- yk1_14
親権者 -- yk1_15

yk1_2 -- 被養育者
yk1_3 -- 被養育者
yk1_4 -- 被養育者
yk1_5 -- 被養育者
yk1_6 -- 被養育者
yk1_7 -- 被養育者
yk1_8 -- 被養育者
yk1_9 -- 被養育者
yk1_11 -- 被養育者
yk1_12 -- 被養育者
yk1_13 -- 被養育者
yk1_14 -- 被養育者
yk1_15 -- 被養育者

システム管理者 -- kanri_1
システム管理者 -- kanri_2
システム管理者 -- kanri_3
システム管理者 -- kanri_4
システム管理者 -- kanri_5
システム管理者 -- kanri_6
システム管理者 -- kanri_7
システム管理者 -- kanri_8
システム管理者 -- kanri_9

@enduml