version: '3.8'

services:
  redmine:
    image: redmine
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: password
    depends_on:
      - db
    restart: always

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: redmine
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes_from:
      - datastore
    restart: always

  datastore:
    image: busybox
    volumes:
      - redmine-data:/var/lib/mysql

volumes:
  redmine-data:
    driver: local